### ISSUE TITLE
[text highlight] Selected text is highlighted too

### ISSUE THREAD

**Issue by comanjoni** [zikicm/github-sublime#34]
Selected text is highlighted too. All texts except selected should be highlighted.

**Comment by zikicm** [comment]
I am not sure if this is actually a bug. For me, it would be a nice behaviour.

**Comment by comanjoni** [comment]
I think that you have right. After latest work on this feature text is highlighted only when whole word is selected. So this "issue" actually indicates that there might be highlighted strings.
I'll close this issue for now.
